import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { existsSync } from 'node:fs';
import { createServer } from '../server.js';

const runtime = 'C:/Users/<user>/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright';
const executablePath = 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
const require = createRequire(import.meta.url);

test('workspace edits, persistence, protected recovery and design roundtrip', { skip: !existsSync(runtime) || !existsSync(executablePath) }, async () => {
  const server = createServer();
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const { chromium } = require(runtime);
  const browser = await chromium.launch({ headless: true, executablePath });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    for (const id of ['studio-title', 'studio-subtitle', 'studio-footer', 'studio-speech-title']) assert.equal(await page.locator(`#${id}`).count(), 0);
    await page.locator('#enter-talk').click();
    const initialCount = await page.locator('.stage-comment').count();
    const initialSize = await page.locator('.stage-comment p').first().evaluate(element => getComputedStyle(element).fontSize);
    await page.locator('#stage-font-plus').click();
    assert.equal(await page.locator('.stage-comment p').first().evaluate(element => getComputedStyle(element).fontSize), `${parseFloat(initialSize) + 2}px`);
    assert.equal(await page.locator('.stage-comment').count(), initialCount);
    await page.locator('#stage-font-minus').click();
    for (const [id, label, key] of [['stage-title', '配信タイトル', 'title'], ['stage-subtitle', 'ひとこと', 'subtitle'], ['stage-footer-text', '画面下の文章', 'footer'], ['stage-speech-title', '読み上げ枠の見出し', 'speechTitle']]) {
      await page.locator(`#${id}`).hover();
      const alignment = await page.locator(`#${id}`).evaluate(element => {
        const text = element.getBoundingClientRect(), pencil = element.parentElement.querySelector('.stage-edit-pencil').getBoundingClientRect();
        return Math.abs((text.top + text.bottom) / 2 - (pencil.top + pencil.bottom) / 2);
      });
      assert.ok(alignment < 2, `${label}: pencil center differs by ${alignment}px`);
      await page.getByRole('button', { name: `${label}を編集`, exact: true }).click();
      assert.equal(await page.locator('.stage-text-dialog').evaluate(dialog => dialog.matches(':modal')), true);
      await page.getByRole('textbox', { name: label, exact: true }).fill(`<新しい${label}>`);
      await page.locator('.stage-text-editor').getByRole('button', { name: '保存', exact: true }).click();
      assert.equal(await page.locator(`#${id}`).textContent(), `<新しい${label}>`);
      assert.equal(await page.evaluate(key => JSON.parse(localStorage.getItem('pokome-studio'))[key], key), `<新しい${label}>`);
    }
    await page.locator('#stage-title').hover();
    await page.getByRole('button', { name: '配信タイトルを編集', exact: true }).click();
    await page.getByRole('textbox', { name: '配信タイトル', exact: true }).fill('保存しない');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#talk-stage').isVisible(), true);
    assert.equal(await page.locator('#stage-title').textContent(), '<新しい配信タイトル>');
    await page.keyboard.press('Escape');
    await page.reload();
    assert.equal(await page.locator('#stage-title').textContent(), '<新しい配信タイトル>');
    await page.locator('[data-page="studio"]').click();
    await page.locator('#studio-list-count').fill('3');
    await page.locator('#studio-list-count').dispatchEvent('change');
    await page.locator('#preview-talk').click();
    assert.equal(await page.locator('.stage-comment').count(), 3);
    await page.keyboard.press('Escape');
    await page.locator('[data-page="home"]').click();
    const editor = page.locator('#workspace-editor');
    const session = page.locator('#layout-session');
    assert.equal(await editor.isVisible(), false);
    assert.equal(await session.isVisible(), false);
    await page.locator('[data-page="studio"]').click();
    await editor.locator('#edit').click();
    assert.equal(await session.isVisible(), true);
    await session.locator('#finish').click();
    await editor.locator('.fields summary').click();
    assert.equal(await editor.locator('#x').getAttribute('aria-describedby'), 'x-help');
    await editor.locator('#x').fill('10');
    await editor.locator('#x').dispatchEvent('change');
    await editor.locator('#w').fill('45');
    await editor.locator('#w').dispatchEvent('change');
    await editor.locator('#edit').click();
    const move = page.getByRole('button', { name: 'コメント一覧 を移動', exact: true });
    const before = await move.boundingBox();
    await page.mouse.move(before.x + 12, before.y + 10);
    await page.mouse.down();
    await page.mouse.move(before.x + 65, before.y + 30, { steps: 4 });
    await page.mouse.up();
    const resize = page.getByRole('button', { name: 'コメント一覧 のサイズ変更', exact: true });
    const handle = await resize.boundingBox();
    await page.mouse.move(handle.x + 8, handle.y + 8);
    await page.mouse.down();
    await page.mouse.move(handle.x + 38, handle.y + 28, { steps: 4 });
    await page.mouse.up();
    const home = await page.evaluate(() => JSON.parse(localStorage.getItem('pokome-workspace-v1')).home);
    assert.ok(home.panels.comments.x > 10);
    assert.ok(home.panels.comments.w > 45);
    await page.reload();
    assert.equal(await session.isVisible(), false);
    assert.equal(await page.locator('.comments').evaluate(element => element.style.left), `${home.panels.comments.x}%`);
    await page.locator('[data-page="studio"]').click();
    await editor.locator('#mode').selectOption('talk');
    await editor.locator('#edit').click();
    await session.locator('#finish').click();
    await editor.locator('.fields summary').click();
    await editor.locator('#hidden').check();
    await page.locator('#preview-talk').click();
    await page.locator('.stage-header').waitFor({ state: 'hidden' });
    await page.keyboard.press('Escape');
    await page.locator('[data-page="studio"]').click();
    await editor.locator('#edit').click();
    await session.locator('#finish').click();
    await page.locator('#talk-stage').waitFor({ state: 'hidden' });
    await page.locator('[data-page="studio"]').click();
    await page.locator('#theme-css').locator('xpath=ancestor::details').locator('summary').click();
    await page.locator('#theme-css').fill('.pokome-workspace .pokome-panel { border-radius: 3px; }');
    await page.locator('#theme-apply').click();
    assert.match(await page.locator('#pokome-user-theme').textContent(), /border-radius: 3px/);
    await page.locator('#theme-import').setInputFiles({ name: 'theme.css', mimeType: 'text/css', buffer: Buffer.from('.pokome-workspace { color: rgb(1, 2, 3); }') });
    await page.waitForFunction(() => document.querySelector('#pokome-user-theme').textContent.includes('rgb(1, 2, 3)'));
    const downloadEvent = page.waitForEvent('download');
    await page.locator('#design-export').click();
    const download = await downloadEvent;
    const stream = await download.createReadStream();
    const chunks = [];
    for await (const chunk of stream) chunks.push(chunk);
    const exported = Buffer.concat(chunks);
    const design = JSON.parse(exported.toString());
    assert.deepEqual(design.layout.home, home);
    assert.equal(design.layout.talk.panels.header.hidden, true);
    await page.locator('#theme-reset').click();
    await page.locator('#theme-import').setInputFiles({ name: 'design.json', mimeType: 'application/json', buffer: exported });
    await page.waitForFunction(() => document.querySelector('#pokome-user-theme').textContent.includes('rgb(1, 2, 3)'));
    assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('pokome-workspace-v1'))), design.layout);
    assert.deepEqual(errors, []);
  } finally {
    await browser.close();
    await new Promise(resolve => server.close(resolve));
  }
});
